name: Github Actions CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: ${{ matrix.os }} ${{ matrix.compiler }} ${{ matrix.build_type }}
    runs-on: ${{ matrix.runs_on }}
    strategy:
      fail-fast: True
      max-parallel: 1
      matrix:
        os: [Ubuntu, Windows]
        build_type: [Debug, Release]
        include:
          - os: Windows
            compiler: MSVC
            c_compiler: cl
            cxx_compiler: cl
            generator: Visual Studio 17 2022
            build_type_variable: CMAKE_CONFIGURATION_TYPES
            runs_on: windows-2022
          # - os: MacOS (ARM64)
          #   compiler: AppleClang
          #   c_compiler: cc
          #   cxx_compiler: c++
          #   generator: Xcode
          #   build_type_variable: CMAKE_CONFIGURATION_TYPES
          #   runs_on: macos-14
          # - os: MacOS (AMD64)
          #   compiler: AppleClang
          #   c_compiler: cc
          #   cxx_compiler: c++
          #   generator: Xcode
          #   build_type_variable: CMAKE_CONFIGURATION_TYPES
          #   runs_on: macos-13
          - os: Ubuntu
            compiler: Gcc
            c_compiler: gcc-14
            cxx_compiler: g++-14
            generator: Ninja
            build_type_variable: CMAKE_BUILD_TYPE
            runs_on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: True

      - uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - uses: lukka/get-cmake@latest

      - name: Xcode Select Version
        if: ${{ startsWith(matrix.os, 'MacOS') }}
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '15.0.1'

      - name: Install Extra Packages
        if: ${{ matrix.os == 'Ubuntu' }}
        run: |
          sudo add-apt-repository universe
          sudo apt-get update
          sudo apt-get install -y libx11-dev libx11-xcb-dev libfontenc-dev libice-dev libsm-dev libxau-dev libxaw7-dev libxcomposite-dev libxcursor-dev libxdamage-dev libxdmcp-dev libxext-dev libxfixes-dev libxi-dev libxinerama-dev libxkbfile-dev libxmu-dev libxmuu-dev libxpm-dev libxrandr-dev libxrender-dev libxres-dev libxss-dev libxt-dev libxtst-dev libxv-dev libxxf86vm-dev libxcb-glx0-dev libxcb-render0-dev libxcb-render-util0-dev libxcb-xkb-dev libxcb-icccm4-dev libxcb-image0-dev libxcb-keysyms1-dev libxcb-randr0-dev libxcb-shape0-dev libxcb-sync-dev libxcb-xfixes0-dev libxcb-xinerama0-dev libxcb-dri3-dev uuid-dev libxcb-cursor-dev libxcb-dri2-0-dev libxcb-dri3-dev libxcb-present-dev libxcb-composite0-dev libxcb-ewmh-dev libxcb-res0-dev libxcb-util-dev libxcb-util0-dev
          sudo apt-get install gcc-14 g++-14

      - name: Install Conan
        run: |
            python -m pip install --upgrade pip
            pip install conan
            conan --version
            conan profile detect --force

      - name: Cache Conan
        uses: actions/cache@v4.2.0
        with:
          path: |
            ./.conan_home
          key: ${{ matrix.os }}-${{ matrix.build_type }}-conan-cpp23-${{ hashFiles('conanfile.py') }}

      - name: Configure
        run: |
          mkdir build
          cd build
          cmake .. -Wno-dev -DPPP_BUILD_TESTS=ON -DPPP_FORMAT_TARGETS=OFF -G"${{matrix.generator}}" -D${{matrix.build_type_variable}}=${{matrix.build_type}} -DCMAKE_C_COMPILER=${{matrix.c_compiler}} -DCMAKE_CXX_COMPILER=${{matrix.cxx_compiler}}

      - name: Build
        run: |
            cd build
            cmake --build . --config ${{matrix.build_type}}

      - name: Test
        run: |
            cd build
            ctest . -C ${{matrix.build_type}} --output-on-failure
