name: Github Actions CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: ${{ matrix.os }} ${{ matrix.compiler }} ${{ matrix.build_type }}
    runs-on: ${{ matrix.runs_on }}
    strategy:
      fail-fast: True
      max-parallel: 1
      matrix:
        os: [MacOS, Ubuntu, Windows]
        build_type: [Debug, Release]
        include:
          - os: Windows
            compiler: MSVC
            runs_on: windows-2022
          - os: MacOS
            compiler: AppleClang
            runs_on: macos-14
          - os: Ubuntu
            compiler: Gcc
            runs_on: ubuntu-24.04

    steps:
      - name: Free Disk Space (Ubuntu)
        if: ${{ matrix.os == 'Ubuntu' }}
        uses: jlumbroso/free-disk-space@v1.3.1
        with:
          tool-cache: false

      - uses: actions/checkout@v4
        with:
          submodules: True

      - uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - uses: lukka/get-cmake@latest

      - name: Xcode Select Version
        if: ${{ matrix.os == 'MacOS' }}
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '15.4'

      - name: Install Extra Packages (Ubuntu)
        if: ${{ matrix.os == 'Ubuntu' }}
        run: |
          sudo add-apt-repository universe
          sudo apt-get update
          sudo apt-get install -y libx11-dev libx11-xcb-dev libfontenc-dev libice-dev libsm-dev libxau-dev libxaw7-dev libxcomposite-dev libxcursor-dev libxdamage-dev libxdmcp-dev libxext-dev libxfixes-dev libxi-dev libxinerama-dev libxkbfile-dev libxmu-dev libxmuu-dev libxpm-dev libxrandr-dev libxrender-dev libxres-dev libxss-dev libxt-dev libxtst-dev libxv-dev libxxf86vm-dev libxcb-glx0-dev libxcb-render0-dev libxcb-render-util0-dev libxcb-xkb-dev libxcb-icccm4-dev libxcb-image0-dev libxcb-keysyms1-dev libxcb-randr0-dev libxcb-shape0-dev libxcb-sync-dev libxcb-xfixes0-dev libxcb-xinerama0-dev libxcb-dri3-dev uuid-dev libxcb-cursor-dev libxcb-dri2-0-dev libxcb-dri3-dev libxcb-present-dev libxcb-composite0-dev libxcb-ewmh-dev libxcb-res0-dev libxcb-util-dev libxcb-util0-dev
          sudo apt-get install gcc-14 g++-14

      - name: Install Conan
        run: |
            python -m pip install --upgrade pip
            pip install conan
            conan --version
            conan profile detect --force

      - name: Conan set Xcode Generator (MacOS)
        if: ${{ matrix.os == 'MacOS' }}
        run: |
          cd .conan_home/profiles
          echo "[conf]" >> default
          echo "tools.cmake.cmaketoolchain:generator=Xcode" >> default
          
      - name: Configure (MacOS)
        if: ${{ matrix.os == 'MacOS' }}
        run: |
          mkdir build
          cd build
          cmake .. -Wno-dev -DPPP_BUILD_TESTS=ON -DPPP_FORMAT_TARGETS=OFF -GXcode -DCMAKE_CONFIGURATION_TYPES=${{matrix.build_type}} -DCMAKE_C_COMPILER=cc -DCMAKE_CXX_COMPILER=c++ -DCMAKE_OSX_ARCHITECTURES="x86_64;arm64" -DCMAKE_OSX_DEPLOYMENT_TARGET="11.0"

      - name: Configure (Ubuntu)
        if: ${{ matrix.os == 'Ubuntu' }}
        run: |
          mkdir build
          cd build
          cmake .. -Wno-dev -DPPP_BUILD_TESTS=ON -DPPP_FORMAT_TARGETS=OFF -GNinja -DCMAKE_BUILD_TYPE=${{matrix.build_type}} -DCMAKE_C_COMPILER=gcc-14 -DCMAKE_CXX_COMPILER=g++-14

      - name: Configure (Windows)
        if: ${{ matrix.os == 'Windows' }}
        run: |
          mkdir build
          cd build
          cmake .. -Wno-dev -DPPP_BUILD_TESTS=ON -DPPP_FORMAT_TARGETS=OFF -G"Visual Studio 17 2022" -DCMAKE_CONFIGURATION_TYPES=${{matrix.build_type}} -DCMAKE_C_COMPILER=cl -DCMAKE_CXX_COMPILER=cl

      - name: Build
        run: |
            cd build
            cmake --build . --config ${{matrix.build_type}}

      - name: Test
        run: |
            cd build
            ctest . -C ${{matrix.build_type}} --output-on-failure
