name: Github Actions Publish

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    name: ${{ matrix.os }} ${{ matrix.compiler }}
    runs-on: ${{ matrix.runs_on }}
    strategy:
      fail-fast: True
      max-parallel: 1
      matrix:
        os: [Ubuntu, Windows]
        include:
          - os: Windows
            compiler: MSVC
            c_compiler: cl
            cxx_compiler: cl
            generator: Visual Studio 17 2022
            build_type_variable: CMAKE_CONFIGURATION_TYPES
            runs_on: windows-2022
            asset_name: ${{ github.event.repository.name }}-${{ github.ref_name }}-windows_amd64.zip
          - os: Ubuntu
            compiler: Gcc
            c_compiler: gcc-14
            cxx_compiler: g++-14
            generator: Ninja
            build_type_variable: CMAKE_BUILD_TYPE
            runs_on: ubuntu-24.04
            asset_name: ${{ github.event.repository.name }}-${{ github.ref_name }}-ubuntu_amd64.zip

    steps:
      - name: Free Disk Space (Ubuntu)
        if: ${{ matrix.os == 'Ubuntu' }}
        uses: jlumbroso/free-disk-space@v1.3.1
        with:
          tool-cache: false

      - uses: actions/checkout@v4
        with:
          submodules: True

      - uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - uses: lukka/get-cmake@latest

      - name: Install Extra Packages (Ubuntu)
        if: ${{ matrix.os == 'Ubuntu' }}
        run: |
          sudo add-apt-repository universe
          sudo apt-get update
          sudo apt-get install -y libx11-dev libx11-xcb-dev libfontenc-dev libice-dev libsm-dev libxau-dev libxaw7-dev libxcomposite-dev libxcursor-dev libxdamage-dev libxdmcp-dev libxext-dev libxfixes-dev libxi-dev libxinerama-dev libxkbfile-dev libxmu-dev libxmuu-dev libxpm-dev libxrandr-dev libxrender-dev libxres-dev libxss-dev libxt-dev libxtst-dev libxv-dev libxxf86vm-dev libxcb-glx0-dev libxcb-render0-dev libxcb-render-util0-dev libxcb-xkb-dev libxcb-icccm4-dev libxcb-image0-dev libxcb-keysyms1-dev libxcb-randr0-dev libxcb-shape0-dev libxcb-sync-dev libxcb-xfixes0-dev libxcb-xinerama0-dev libxcb-dri3-dev uuid-dev libxcb-cursor-dev libxcb-dri2-0-dev libxcb-dri3-dev libxcb-present-dev libxcb-composite0-dev libxcb-ewmh-dev libxcb-res0-dev libxcb-util-dev libxcb-util0-dev
          sudo apt-get install gcc-14 g++-14

      - name: Cache Conan
        uses: actions/cache@v4.2.0
        with:
          path: |
            ./.conan_home
          key: ${{ matrix.os }}-Release-conan-cpp23-${{ hashFiles('conanfile.py') }}

      - name: Install Conan
        run: |
            python -m pip install --upgrade pip
            pip install conan
            conan --version
            conan profile detect --force

      - name: Configure (Ubuntu)
        if: ${{ matrix.os == 'Ubuntu' }}
        run: |
          mkdir build
          cd build
          cmake .. -Wno-dev -DPPP_BUILD_TESTS=OFF -DPPP_FORMAT_TARGETS=OFF -GNinja -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER=gcc-14 -DCMAKE_CXX_COMPILER=g++-14

      - name: Configure (Windows)
        if: ${{ matrix.os == 'Windows' }}
        run: |
          mkdir build
          cd build
          cmake .. -Wno-dev -DPPP_BUILD_TESTS=OFF -DPPP_FORMAT_TARGETS=OFF -G"Visual Studio 17 2022" -DCMAKE_CONFIGURATION_TYPES=Release -DCMAKE_C_COMPILER=cl -DCMAKE_CXX_COMPILER=cl

      - name: Build
        run: |
            cd build
            cmake --build . --config Release

      - name: Install
        run: |
          cd build
          cmake --install . --config Release

      - name: Get Release Notes
        id: extract_release_notes
        uses: ffurrer2/extract-release-notes@v2.2.0

      - name: Zip Release
        run: |
          cd publish
          tar -a -c -f ../${{ matrix.asset_name }} *

      - name: Upload Binaries
        uses: svenstaro/upload-release-action@2.9.0
        with:
          release_name: Release ${{ github.ref }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ matrix.asset_name }}
          asset_name: ${{ matrix.asset_name }}
          tag: ${{ github.ref }}
          body: ${{ steps.extract_release_notes.outputs.release_notes }}
          draft: false
